# Generated by Django 4.2.10 on 2024-02-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('output', models.TextField()),
                ('cronjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.cronjob')),
            ],
        ),
    ]
